### ISSUE TITLE
Laravel can't find Bugsnag driver

### ISSUE THREAD

**Issue by rbresjer** [bugsnag/bugsnag-laravel#333]
### Expected behavior
Exceptions are sent to Bugsnag.

### Observed behavior
Laravel can't find the Bugsnag driver and therefore logs to the emergency log:
```
[2018-11-05 15:12:37] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [bugsnag] is not supported. at /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:180)
[stacktrace]
#0 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(101): Illuminate\\Log\\LogManager->resolve('bugsnag')
#1 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(89): Illuminate\\Log\\LogManager->get('bugsnag')
#2 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(78): Illuminate\\Log\\LogManager->driver('bugsnag')
#3 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(216): Illuminate\\Log\\LogManager->channel('bugsnag')
#4 [internal function]: Illuminate\\Log\\LogManager->Illuminate\\Log\\{closure}('bugsnag', 2)
#5 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Support/Collection.php(946): array_map(Object(Closure), Array, Array)
#6 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1041): Illuminate\\Support\\Collection->map(Object(Closure))
#7 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(217): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#8 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(177): Illuminate\\Log\\LogManager->createStackDriver(Array)
#9 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(101): Illuminate\\Log\\LogManager->resolve('stack')
#10 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(89): Illuminate\\Log\\LogManager->get('stack')
#11 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(488): Illuminate\\Log\\LogManager->driver()
#12 /home/forge/[site]/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\Log\\LogManager->error('Call to a membe...', Array)
```

### Steps to reproduce
No idea... I thought it worked before, might be broken since a composer update but not sure. Might be that just sending a test exception via the Bugsnag facade worked.

### Version
- laravel/framework v5.7.12
- bugsnag/bugsnag-laravel v2.0.0
- bugsnag/bugsnag v3.15.0

### Additional information
- `config/app.php` contains provider `Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class`
- `.env` contains an API key
- `config/logging.php` contains
```
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'slack', 'bugsnag'],
        ],

        // [..]

        'bugsnag' => [
            'driver' => 'bugsnag',
        ],
```

**Comment by rbresjer** [comment]
I tried clearing everything, but unfortunately the issue persists...

```
$ php artisan |grep clear
  clear-compiled             Remove the compiled class file
  auth:clear-resets          Flush expired password reset tokens
  cache:clear                Flush the application cache
  config:clear               Remove the configuration cache file
  optimize:clear             Remove the cached bootstrap files
  route:clear                Remove the route cache file
  view:clear                 Clear all compiled view files
$ php artisan clear-compiled
Compiled services and packages files removed!
$ php artisan cache:clear
Application cache cleared!
$ php artisan config:clear
Configuration cache cleared!
$ php artisan optimize:clear
Compiled views cleared!
Application cache cleared!
Route cache cleared!
Configuration cache cleared!
Compiled services and packages files removed!
Caches cleared successfully!
$ php artisan route:clear
Route cache cleared!
$ php artisan view:clear
Compiled views cleared!
$ php artisan serve
Laravel development server started: <http://127.0.0.1:8000>
[Thu Nov  8 08:34:01 2018] 127.0.0.1:57982 [200]: /favicon.ico
```

**Comment by rbresjer** [comment]
@ankurk91 Thanks, that was it. Someone forgot the `^` in the composer.json..
