### ISSUE TITLE
'ReflectionException' with message 'Class bugsnag does not exist' 

### ISSUE THREAD

**Issue by Jaspur** [bugsnag/bugsnag-laravel#41]
```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in /home/forge/foobar.nl/storage/framework/compiled.php:1029
Stack trace:
#0 /home/forge/foobar.nl/storage/framework/compiled.php(1029): ReflectionClass->__construct('bugsnag')
#1 /home/forge/foobar.nl/storage/framework/compiled.php(980): Illuminate\Container\Container->build('bugsnag', Array)
#2 /home/forge/foobar.nl/storage/framework/compiled.php(1493): Illuminate\Container\Container->make('bugsnag', Array)
#3 /home/forge/foobar.nl/storage/framework/compiled.php(1213): Illuminate\Foundation\Application->make('bugsnag')
#4 /home/forge/foobar.nl/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagExceptionHandler.php(25): Illuminate\Container\Container->offsetGet('bugsnag')
#5 /home/forge/foobar.nl/app/Exceptions/Handler.php(27): Bugsnag\BugsnagLaravel\BugsnagExceptionHandler->report(Object(ReflectionException))
#6 /home/forge/mijnplusmo in /home/forge/foobar.nl/storage/framework/compiled.php on line 1029
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in /home/forge/foobar.nl/storage/framework/compiled.php:1029
Stack trace:
#0 /home/forge/foobar.nl/storage/framework/compiled.php(1029): ReflectionClass->__construct('bugsnag')
#1 /home/forge/foobar.nl/storage/framework/compiled.php(980): Illuminate\Container\Container->build('bugsnag', Array)
#2 /home/forge/foobar.nl/storage/framework/compiled.php(1493): Illuminate\Container\Container->make('bugsnag', Array)
#3 /home/forge/foobar.nl/storage/framework/compiled.php(1213): Illuminate\Foundation\Application->make('bugsnag')
#4 /home/forge/foobar.nl/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagExceptionHandler.php(25): Illuminate\Container\Container->offsetGet('bugsnag')
#5 /home/forge/foobar.nl/app/Exceptions/Handler.php(27): Bugsnag\BugsnagLaravel\BugsnagExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorExc in /home/forge/foobar.nl/storage/framework/compiled.php on line 1029
```

**Comment by ConradIrwin** [comment]
@Jaspur which version of Laravel are you using? Are you loading the BugsnagLaravelServiceProvider?

**Comment by HebronNor** [comment]
I get this error as well

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in /var/www/staging/uctrl/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /var/www/staging/uctrl/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('bugsnag')
#1 /var/www/staging/uctrl/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\\Container\\Container->build('bugsnag', Array)
#2 /var/www/staging/uctrl/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\\Container\\Container->make('bugsnag', Array)
#3 /var/www/staging/uctrl/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1231): Illuminate\\Foundation\\Application->make('bugsnag')
#4 /var/www/staging/uctrl/laravel/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagExceptionHandler.php(25): Illuminate\\Container\\Container->offsetGet('bugsnag')
#5 /var/www/staging/uctr in /var/www/staging/uctrl/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776
```


I am using Laravel 5.0.16, I am loading the service provider:

```
'Bugsnag\BugsnagLaravel\BugsnagLaravelServiceProvider',
```

And alias:
```
'Bugsnag' => 'Bugsnag\BugsnagLaravel\BugsnagFacade',
```

I resolved it by making the vendor folder writable by the web server, but I don't get why that should be necessary.

**Comment by HebronNor** [comment]
So I did a little bit more testing, I put the permissions on the vendor folder back (not writable by the web-server). No errors until I did a `composer update`, which did not update any packages but it did generate autoload files and optimized class loader.
```

**Comment by snmaynard** [comment]
Glad you solved it (and thanks for letting us know how @HebronNor)!

**Comment by tachu** [comment]
I'm having the exact same error when running in Google app engine. They require you to run composer update from your environment and then deploying to appEngine. The app engine sandbox makes it so you can't write do disk. IS there a workaround for this? Why does it need to be able to write to disk if its already been composed?

t
