### ISSUE TITLE
Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist'

### ISSUE THREAD

**Issue by Kryptonit3** [bugsnag/bugsnag-laravel#53]
Upgrading Laravel 5.0.x to 5.1, when running `composer update` I get the following

~~~
  [RuntimeException]
  Error Output: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\sr
  c\Illuminate\Container\Container.php:765
  Stack trace:
  #0 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php(765): ReflectionClass->__construct('bugsnag')
  #1 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php(645): Illuminate\Container\Container->build('bugsnag', Array)
  #2 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(651): Illuminate\Container\Container->make('bugsnag', Array)
  #3 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php(1220): Illuminate\Foundation\Application->make('bugsnag')
  #4 C:\Users\Jesse\Documents\Projects\cw5\vendor\bugsnag\bugsnag-laravel\src\Bugsnag\BugsnagLaravel\BugsnagExceptionHandler.php(25): Illuminate\Container\Container->off in C:\Users\Jesse
  \Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 765
  PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\C
  ontainer\Container.php:765
  Stack trace:
  #0 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php(765): ReflectionClass->__construct('bugsnag')
  #1 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php(645): Illuminate\Container\Container->build('bugsnag', Array)
  #2 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(651): Illuminate\Container\Container->make('bugsnag', Array)
  #3 C:\Users\Jesse\Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php(1220): Illuminate\Foundation\Application->make('bugsnag')
  #4 C:\Users\Jesse\Documents\Projects\cw5\vendor\bugsnag\bugsnag-laravel\src\Bugsnag\BugsnagLaravel\BugsnagExceptionHandler.php(25): Illuminate\Container\Container->off in C:\Users\Jesse
  \Documents\Projects\cw5\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 765
~~~

Everything is where it needs to be, (service provider, facade).

**Comment by keeganlow** [comment]
Hi @Kryptonit3, would you mind sharing your composer.json file so I can try to recreate the issue?

**Comment by lasselehtinen** [comment]
I've had the same issue in my deployment before. It was resolved by setting the vendor directory writable. I was now doing an upgrade to Laravel 5.1 and seems like I get the same error locally. It does not matter if I run this as admin rights. I am using Windows 7 if it makes any difference.

```php
$ php artisan clear-compiled
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php:736
Stack trace:
#0 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php(736): ReflectionClass->__construct('bugsnag')
#1 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php(626): Illuminate\Container\Container->build('bugsnag', Array)
#2 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(642): Illuminate\Container\Container->make('bugsnag', Array)
#3 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(53): Illuminate\Foundation\Application->make('bugsnag', Array)
#4 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\bugsnag\bugsnag-laravel\src\Bugsnag\B in C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 736
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class bugsnag does not exist' in C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php:736
Stack trace:
#0 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php(736): ReflectionClass->__construct('bugsnag')
#1 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php(626): Illuminate\Container\Container->build('bugsnag', Array)
#2 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(642): Illuminate\Container\Container->make('bugsnag', Array)
#3 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(53): Illuminate\Foundation\Application->make('bugsnag', Array)
#4 C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\bugsnag\bugsnag-laravel\src\Bugsnag\B in C:\Users\lasleh\Dropbox\Development\schilling-rest\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 736
```

Here is my composer.json.

```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.1.*",
		"league/fractal": "0.12.*@dev",
		"zircote/swagger-php": "2.*@dev",
		"guzzlehttp/guzzle": "~5.0",
		"predis/predis": "~1.0",
		"fale/isbn": "2.0.0",
		"cartalyst/sentry": "dev-feature/laravel-5",
		"lasselehtinen/elvis": "2.0.2",
		"venturecraft/revisionable": "1.*",
		"league/csv": "~7.0",
		"ezyang/htmlpurifier": "~4.6",
		"pda/pheanstalk": "~3.0",
		"bugsnag/bugsnag-laravel": "1.*",
		"morrislaptop/laravel-queue-clear": "~1.0"
	},
	"require-dev": {
		"behat/behat": "~3.0",
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database",
			"app/Traits"
		],
		"psr-4": {
			"SchillingRest\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": []
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

**Comment by shazamjad** [comment]
Same issue for me - composer.json:

````
{
  "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
      "php": ">=5.5.9",
      "laravel/framework": "^5.1",
      "illuminate/html": "~5.0",
      "jenssegers/mongodb": "dev-master",
      "predis/predis": "~1.0",
      "maatwebsite/excel": "^2.0",
      "barryvdh/laravel-debugbar": "^2.0",
      "guzzlehttp/guzzle": "^5.1",
      "bugsnag/bugsnag-laravel": "^1.0"
    },
    "require-dev": {
      "phpunit/phpunit": "~4.0",
      "phpspec/phpspec": "~2.1"
    },
    "autoload": {
      "classmap": [
        "database"
        ],
      "psr-4": {
        "aaaaaa\\": "app/"
      }
    },
    "autoload-dev": {
      "classmap": [
        "tests/TestCase.php"
        ]
    },
    "scripts": {
      "post-install-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
        ],
      "post-update-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
        ],
      "post-create-project-cmd": [
        "php -r \"copy('.env.example', '.env');\"",
        "php artisan key:generate"
        ]
    },
    "config": {
      "preferred-install": "dist"
    }
}

````

**Comment by Gavrisimo** [comment]
I got the same error, but what I did is something like this:

1. update composer.json
2. run `composer update`
3. receive that error

Then I followed instructions from http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0 and did the following:

1. Update bootstrap/autoload.php
2. Create bootstrap/cache Directory
3. run `composer update`
4. no errors

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Generating optimized class loader
```

**Comment by Dixens** [comment]
@Gavrisimo that did the trick, thanks!

**Comment by gpmcadam** [comment]
For what it's worth, this issue happened to me because the **bootstrap/cache** directory was not writable by the webserver. Thanks to @Gavrisimo for the tip.
