### ISSUE TITLE
notifyException creates Segmentation fault on Lumen 5.2

### ISSUE THREAD

**Issue by lasselehtinen** [bugsnag/bugsnag-laravel#91]
Hi,

I've noticed that the package segfaults with combination of Lumen 5.2 and PHP 7.0.x. Lumen 5.1 does not seem to be affected. Here are steps to reproduce:

```
composer create-project laravel/lumen bugsnag-lumen-test
cd bugsnag-lumen-test/
composer require bugsnag/bugsnag-laravel:1.*
```

Then add these two lines to app/bootstrap.php after line 83 + set the config for API key.

```
$app->register('Bugsnag\BugsnagLaravel\BugsnagLumenServiceProvider');
app('bugsnag')->notifyException(new Exception("Something bad happened"));
```

If I remove the second line, it works just fine. The backtrace from gdb looks something like this and it just repeats the same three lines.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000774e58 in _zval_copy_ctor_func ()
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x0000000000774e58 in _zval_copy_ctor_func ()
#1  0x00000000007ec447 in ?? ()
#2  0x00000000007b1d2b in execute_ex ()
#3  0x0000000000767109 in dtrace_execute_ex ()
#4  0x00000000007eea40 in ?? ()
#5  0x00000000007b1d2b in execute_ex ()
#6  0x0000000000767109 in dtrace_execute_ex ()
#7  0x00000000007689fc in zend_call_function ()
#8  0x0000000000791df4 in zend_call_method ()
#9  0x00000000007aa300 in zend_std_read_dimension ()
#10 0x00000000007b2c9b in ?? ()
#11 0x00000000007b35aa in ?? ()
#12 0x00000000007b1d2b in execute_ex ()
#13 0x0000000000767109 in dtrace_execute_ex ()
#14 0x00000000007eea40 in ?? ()
#15 0x00000000007b1d2b in execute_ex ()
#16 0x0000000000767109 in dtrace_execute_ex ()
#17 0x00000000007eea40 in ?? ()
#18 0x00000000007b1d2b in execute_ex ()
#19 0x0000000000767109 in dtrace_execute_ex ()
#20 0x00000000007f3cfd in ?? ()
#21 0x00000000007b1d2b in execute_ex ()
#22 0x0000000000767109 in dtrace_execute_ex ()
#23 0x00000000007eea40 in ?? ()
#24 0x00000000007b1d2b in execute_ex ()
#25 0x0000000000767109 in dtrace_execute_ex ()
#26 0x00000000007eea40 in ?? ()
#27 0x00000000007b1d2b in execute_ex ()
#28 0x0000000000767109 in dtrace_execute_ex ()
```

**Comment by kattrali** [comment]
Thank you for the report, @lasselehtinen. I'm taking a look.

**Comment by rap2hpoutre** [comment]
Same problem +1. Does it work with an older version of bugsnag?

**Comment by lasselehtinen** [comment]
@kattrali Any updates on this one? I might have to go live with one Lumen application and I considering if I should downgrade to Lumen 5.1 so I can get the nice Bugsnag reports.

**Comment by lasselehtinen** [comment]
@kattrali I guess I found out the problem. I tested this again on PHP 7.0.3 and now instead of segmentation fault I get the following error:

```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/container/Container.php on line 700
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/bugsnag-lumen-test/public/index.php:0
PHP   2. require() /home/vagrant/Code/bugsnag-lumen-test/public/index.php:14
PHP   3. app() /home/vagrant/Code/bugsnag-lumen-test/bootstrap/app.php:85
PHP   4. Laravel\Lumen\Application->make() /home/vagrant/Code/bugsnag-lumen-test/vendor/laravel/lumen-framework/src/helpers.php:39
PHP   5. Illuminate\Container\Container->make() /home/vagrant/Code/bugsnag-lumen-test/vendor/laravel/lumen-framework/src/Application.php:205
PHP   6. Illuminate\Container\Container->build() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/container/Container.php:631
PHP   7. Bugsnag\BugsnagLaravel\BugsnagLumenServiceProvider->Bugsnag\BugsnagLaravel\{closure}() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/container/Container.php:733
PHP   8. Illuminate\Auth\AuthManager->check() /home/vagrant/Code/bugsnag-lumen-test/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagLumenServiceProvider.php:67
PHP   9. Illuminate\Auth\AuthManager->__call() /home/vagrant/Code/bugsnag-lumen-test/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagLumenServiceProvider.php:67
PHP  10. Illuminate\Auth\AuthManager->guard() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:244
PHP  11. Illuminate\Auth\AuthManager->resolve() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:57
PHP  12. Illuminate\Auth\AuthManager->createApiDriver() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:77
PHP  13. Illuminate\Auth\AuthManager->__call() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:77
PHP  14. Illuminate\Auth\AuthManager->guard() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:244
PHP  15. Illuminate\Auth\AuthManager->resolve() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:57
PHP  16. Illuminate\Auth\AuthManager->createApiDriver() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:77
...
PHP 253. Illuminate\Container\Container->offsetGet() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/auth/AuthManager.php:154
PHP 254. Laravel\Lumen\Application->make() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/container/Container.php:1174
PHP 255. Illuminate\Container\Container->make() /home/vagrant/Code/bugsnag-lumen-test/vendor/laravel/lumen-framework/src/Application.php:205
PHP 256. Illuminate\Container\Container->normalize() /home/vagrant/Code/bugsnag-lumen-test/vendor/illuminate/container/Container.php:616

Fatal error: Maximum function nesting level of '256' reached, aborting! in /home/vagrant/Code/bugsnag-lumen-test/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php on line 54
```
Seems like the culprit is here. The auth check causes a nested loop in Lumen that never gets resolved. Commenting this try block resolves the issue but naturally I won't get the User ID attached. 

https://github.com/bugsnag/bugsnag-laravel/blob/master/src/Bugsnag/BugsnagLaravel/BugsnagLumenServiceProvider.php#L67

**Comment by lasselehtinen** [comment]
Here is a work-around for now. In bootstrap/app.php uncomment the following lines:
```
$app->withFacades();
$app->register(App\Providers\AuthServiceProvider::class);
```

**Comment by rap2hpoutre** [comment]
@kattrali Any updates?

**Comment by GrahamCampbell** [comment]
It looks like we have an infinite loop resolving the current user here.

**Comment by GrahamCampbell** [comment]
I guess this is happening because the authentication stuff hasn't been bootstrapped. I'm not quite sure how we can detect this. It looks like a bug in Lumen itself that the manager can go into a loop like this, but we definitely need to look into us avoiding it.

**Comment by GrahamCampbell** [comment]
I'm going to have a chat with Taylor about this.

**Comment by GrahamCampbell** [comment]
This was fixed by https://github.com/laravel/framework/commit/511e7ab0e5c9f3f84608fb5431cccb8d7ebdbe08. Please let me know if you're still experiencing any issues. :)

**Comment by catalinux** [comment]
I have the same problem with Lumen when I use

```php

        $this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
        $this->app->alias('bugsnag.logger', \Psr\Log\LoggerInterface::class);
```

From docs:
> If you’d like to keep logging to your original logger as well as Bugsnag, you can bind 'bugsnag.multi' rather than 'bugsnag.logger

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. It looks like you're using the Laravel way rather than the Lumen way.

You can read about the Lumen way on our Lumen specific docs:

> https://docs.bugsnag.com/platforms/php/lumen/#reporting-unhandled-exceptions.

---

We're also planning to update our Laravel docs to make it clearer that we have Lumen docs too.

**Comment by catalinux** [comment]
@GrahamCampbell you are right. My fault
